export const expenseColors = {
  background: '#f5f5f5',
  card: '#1976D2',
  text: '#222',
  inputTitle: '#36A2EB',
  inputCategory: '#FF6384',
  inputAmount: '#FFCE56',
  inputAmountText: '#333',
  inputBorder: '#fff',
  button: '#1976D2',
  buttonText: '#fff',
  expenseCard: '#fff',
  expenseAmount: '#1976D2',
  expenseCategory: '#888',
  expenseDate: '#aaa',
  shadow: '#000',
};

export const expenseStyles = {
  container: {
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: expenseColors.background,
  },
  formCard: {
    backgroundColor: expenseColors.card,
    borderRadius: 16,
    padding: 18,
    shadowColor: expenseColors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 3,
    width: '100%',
    maxWidth: 400,
  },
  input: {
    marginVertical: 7,
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    color: expenseColors.buttonText,
    borderWidth: 1.5,
    borderColor: expenseColors.inputBorder,
  },
  inputTitle: {
    backgroundColor: expenseColors.inputTitle,
  },
  inputCategory: {
    backgroundColor: expenseColors.inputCategory,
  },
  inputAmount: {
    backgroundColor: expenseColors.inputAmount,
    color: expenseColors.inputAmountText,
    borderColor: expenseColors.inputAmountText,
  },
  buttonWrapper: {
    marginTop: 12,
    borderRadius: 8,
    overflow: 'hidden',
  },
  expenseCard: {
    backgroundColor: expenseColors.expenseCard,
    borderRadius: 10,
    padding: 12,
    marginVertical: 6,
    marginHorizontal: 2,
    shadowColor: expenseColors.shadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  expenseRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
  },
  expenseTitle: {
    fontWeight: 'bold',
    color: expenseColors.text,
    fontSize: 16,
  },
  expenseAmount: {
    color: expenseColors.expenseAmount,
    fontWeight: 'bold',
    fontSize: 16,
  },
  expenseCategory: {
    color: expenseColors.expenseCategory,
    fontSize: 14,
    fontStyle: 'italic',
  },
  expenseDate: {
    color: expenseColors.expenseDate,
    fontSize: 13,
  },
};
